import type { NewAffirmation } from '../schema/affirmations.js';

export const AFFIRMATION_SEED: NewAffirmation[] = [
  // Anxiety & Stress (20)
  { id: 'anx1', text: "It's okay to not be okay today", categoryId: 'anxiety' },
  { id: 'anx2', text: "Your anxiety is lying to you", categoryId: 'anxiety' },
  { id: 'anx3', text: "You don't have to have it all figured out", categoryId: 'anxiety' },
  { id: 'anx4', text: "Breathing is enough right now", categoryId: 'anxiety' },
  { id: 'anx5', text: "This feeling will pass. It always does.", categoryId: 'anxiety' },
  { id: 'anx6', text: "You've survived every bad day so far", categoryId: 'anxiety' },
  { id: 'anx7', text: "Your worst-case scenario is rarely the real one", categoryId: 'anxiety' },
  { id: 'anx8', text: "You don't have to solve everything today", categoryId: 'anxiety' },
  { id: 'anx9', text: "It's okay to ask for help", categoryId: 'anxiety' },
  { id: 'anx10', text: "You are not your anxious thoughts", categoryId: 'anxiety' },
  { id: 'anx11', text: "Worrying doesn't change the outcome", categoryId: 'anxiety' },
  { id: 'anx12', text: "Your nervous system is just trying to protect you", categoryId: 'anxiety' },
  { id: 'anx13', text: "You can feel afraid and still be brave", categoryId: 'anxiety' },
  { id: 'anx14', text: "Not everything that feels urgent is urgent", categoryId: 'anxiety' },
  { id: 'anx15', text: "You're allowed to take things slow", categoryId: 'anxiety' },
  { id: 'anx16', text: "The anxiety will ease. Give it time.", categoryId: 'anxiety' },
  { id: 'anx17', text: "You don't have to respond to every thought", categoryId: 'anxiety' },
  { id: 'anx18', text: "Ground yourself. You're safe right now.", categoryId: 'anxiety' },
  { id: 'anx19', text: "It's okay to need a moment", categoryId: 'anxiety' },
  { id: 'anx20', text: "Your feelings are valid, even the hard ones", categoryId: 'anxiety' },

  // Winter Darkness (15)
  { id: 'win1', text: "The sun will return, and so will you", categoryId: 'winter' },
  { id: 'win2', text: "Rest is not giving up", categoryId: 'winter' },
  { id: 'win3', text: "Spring always comes, even when it feels impossible", categoryId: 'winter' },
  { id: 'win4', text: "It's okay to move slower in the dark months", categoryId: 'winter' },
  { id: 'win5', text: "You're not lazy. It's literally darker outside.", categoryId: 'winter' },
  { id: 'win6', text: "Hibernating is a natural response", categoryId: 'winter' },
  { id: 'win7', text: "The light will come back", categoryId: 'winter' },
  { id: 'win8', text: "You don't have to be productive. Just survive.", categoryId: 'winter' },
  { id: 'win9', text: "Warmth exists, even in the cold", categoryId: 'winter' },
  { id: 'win10', text: "This season will end", categoryId: 'winter' },
  { id: 'win11', text: "Seek small comforts. They matter.", categoryId: 'winter' },
  { id: 'win12', text: "Your body knows what it needs right now", categoryId: 'winter' },
  { id: 'win13', text: "Darkness makes the light more precious", categoryId: 'winter' },
  { id: 'win14', text: "You're allowed to need more rest in winter", categoryId: 'winter' },
  { id: 'win15', text: "Keep going. Spring is on its way.", categoryId: 'winter' },

  // Energy & Motivation (20)
  { id: 'eng1', text: "Small steps still move you forward", categoryId: 'energy' },
  { id: 'eng2', text: "You're doing better than you think", categoryId: 'energy' },
  { id: 'eng3', text: "Progress isn't always visible", categoryId: 'energy' },
  { id: 'eng4', text: "Just showing up is enough some days", categoryId: 'energy' },
  { id: 'eng5', text: "You don't need to be perfect to begin", categoryId: 'energy' },
  { id: 'eng6', text: "Momentum builds slowly. Keep going.", categoryId: 'energy' },
  { id: 'eng7', text: "Done is better than perfect", categoryId: 'energy' },
  { id: 'eng8', text: "You've done hard things before", categoryId: 'energy' },
  { id: 'eng9', text: "Start where you are", categoryId: 'energy' },
  { id: 'eng10', text: "Every expert was once a beginner", categoryId: 'energy' },
  { id: 'eng11', text: "Your effort counts, even when results are slow", categoryId: 'energy' },
  { id: 'eng12', text: "You're capable of more than you know", categoryId: 'energy' },
  { id: 'eng13', text: "One small thing today is enough", categoryId: 'energy' },
  { id: 'eng14', text: "Keep the faith in yourself", categoryId: 'energy' },
  { id: 'eng15', text: "You're still here. That's strength.", categoryId: 'energy' },
  { id: 'eng16', text: "Your pace is valid", categoryId: 'energy' },
  { id: 'eng17', text: "Slow progress is still progress", categoryId: 'energy' },
  { id: 'eng18', text: "You can start again anytime", categoryId: 'energy' },
  { id: 'eng19', text: "Rest first if you need to", categoryId: 'energy' },
  { id: 'eng20', text: "You're allowed to try again tomorrow", categoryId: 'energy' },

  // Self-Care (18)
  { id: 'sc1', text: "Rest is productive", categoryId: 'self-care' },
  { id: 'sc2', text: "Saying no is okay", categoryId: 'self-care' },
  { id: 'sc3', text: "You matter, even when you're not producing", categoryId: 'self-care' },
  { id: 'sc4', text: "Your needs are valid", categoryId: 'self-care' },
  { id: 'sc5', text: "You don't have to earn rest", categoryId: 'self-care' },
  { id: 'sc6', text: "It's not selfish to take care of yourself", categoryId: 'self-care' },
  { id: 'sc7', text: "Your worth isn't tied to your productivity", categoryId: 'self-care' },
  { id: 'sc8', text: "Take the break. You've earned it.", categoryId: 'self-care' },
  { id: 'sc9', text: "You can't pour from an empty cup", categoryId: 'self-care' },
  { id: 'sc10', text: "Being kind to yourself isn't weakness", categoryId: 'self-care' },
  { id: 'sc11', text: "You deserve gentleness", categoryId: 'self-care' },
  { id: 'sc12', text: "Boundaries protect your peace", categoryId: 'self-care' },
  { id: 'sc13', text: "It's okay to put yourself first sometimes", categoryId: 'self-care' },
  { id: 'sc14', text: "You're allowed to cancel plans", categoryId: 'self-care' },
  { id: 'sc15', text: "Listen to what your body needs", categoryId: 'self-care' },
  { id: 'sc16', text: "Taking care of yourself helps you take care of others", categoryId: 'self-care' },
  { id: 'sc17', text: "You don't owe anyone your energy", categoryId: 'self-care' },
  { id: 'sc18', text: "Choosing yourself isn't abandoning others", categoryId: 'self-care' },

  // Mindfulness (15)
  { id: 'mf1', text: "This moment is enough", categoryId: 'mindfulness' },
  { id: 'mf2', text: "Be here, now", categoryId: 'mindfulness' },
  { id: 'mf3', text: "You don't have to be anywhere else", categoryId: 'mindfulness' },
  { id: 'mf4', text: "Notice what's good right now", categoryId: 'mindfulness' },
  { id: 'mf5', text: "Breathe. Just breathe.", categoryId: 'mindfulness' },
  { id: 'mf6', text: "This moment won't last forever", categoryId: 'mindfulness' },
  { id: 'mf7', text: "Feel your feet on the ground", categoryId: 'mindfulness' },
  { id: 'mf8', text: "You're here. That's enough.", categoryId: 'mindfulness' },
  { id: 'mf9', text: "Let the moment be what it is", categoryId: 'mindfulness' },
  { id: 'mf10', text: "Notice without judging", categoryId: 'mindfulness' },
  { id: 'mf11', text: "Come back to your breath", categoryId: 'mindfulness' },
  { id: 'mf12', text: "Right now is all there is", categoryId: 'mindfulness' },
  { id: 'mf13', text: "Pause and feel what you feel", categoryId: 'mindfulness' },
  { id: 'mf14', text: "You don't have to figure it all out right now", categoryId: 'mindfulness' },
  { id: 'mf15', text: "Let go of the next moment for a second", categoryId: 'mindfulness' },

  // Sleep & Rest (15)
  { id: 'sl1', text: "Tomorrow is a new chance", categoryId: 'sleep' },
  { id: 'sl2', text: "Let today go. It's done.", categoryId: 'sleep' },
  { id: 'sl3', text: "Your body deserves rest", categoryId: 'sleep' },
  { id: 'sl4', text: "The worries can wait until morning", categoryId: 'sleep' },
  { id: 'sl5', text: "You did enough today", categoryId: 'sleep' },
  { id: 'sl6', text: "Sleep is healing", categoryId: 'sleep' },
  { id: 'sl7', text: "Release the day", categoryId: 'sleep' },
  { id: 'sl8', text: "You're safe to rest now", categoryId: 'sleep' },
  { id: 'sl9', text: "Tomorrow will handle itself", categoryId: 'sleep' },
  { id: 'sl10', text: "Let your mind quiet", categoryId: 'sleep' },
  { id: 'sl11', text: "Nothing needs your attention right now", categoryId: 'sleep' },
  { id: 'sl12', text: "You can think about that tomorrow", categoryId: 'sleep' },
  { id: 'sl13', text: "Rest well. You've earned it.", categoryId: 'sleep' },
  { id: 'sl14', text: "The night is for letting go", categoryId: 'sleep' },
  { id: 'sl15', text: "Close your eyes. Tomorrow will wait.", categoryId: 'sleep' },

  // Focus (15)
  { id: 'fc1', text: "One thing at a time is enough", categoryId: 'focus' },
  { id: 'fc2', text: "You don't have to do everything", categoryId: 'focus' },
  { id: 'fc3', text: "What's the one thing that matters most?", categoryId: 'focus' },
  { id: 'fc4', text: "Multitasking is a myth", categoryId: 'focus' },
  { id: 'fc5', text: "Start with one small step", categoryId: 'focus' },
  { id: 'fc6', text: "You can only do what you can do", categoryId: 'focus' },
  { id: 'fc7', text: "Focus on what you can control", categoryId: 'focus' },
  { id: 'fc8', text: "The rest can wait", categoryId: 'focus' },
  { id: 'fc9', text: "Single-tasking is a superpower", categoryId: 'focus' },
  { id: 'fc10', text: "Do one thing well", categoryId: 'focus' },
  { id: 'fc11', text: "It's okay to ignore everything else for now", categoryId: 'focus' },
  { id: 'fc12', text: "Protect your attention", categoryId: 'focus' },
  { id: 'fc13', text: "You don't need to respond to everything", categoryId: 'focus' },
  { id: 'fc14', text: "Finish one thing before starting another", categoryId: 'focus' },
  { id: 'fc15', text: "Your attention is precious. Guard it.", categoryId: 'focus' },

  // Overthinking (18)
  { id: 'ot1', text: "Your thoughts aren't facts", categoryId: 'overthinking' },
  { id: 'ot2', text: "You can't think your way out of everything", categoryId: 'overthinking' },
  { id: 'ot3', text: "Not every thought deserves your attention", categoryId: 'overthinking' },
  { id: 'ot4', text: "Let it go. You can't control it.", categoryId: 'overthinking' },
  { id: 'ot5', text: "Your brain is just doing its job. It's okay.", categoryId: 'overthinking' },
  { id: 'ot6', text: "Analysis paralysis is real. Just pick one.", categoryId: 'overthinking' },
  { id: 'ot7', text: "You've already thought about this enough", categoryId: 'overthinking' },
  { id: 'ot8', text: "Thinking more won't change the outcome", categoryId: 'overthinking' },
  { id: 'ot9', text: "Trust yourself. You know more than you think.", categoryId: 'overthinking' },
  { id: 'ot10', text: "Stop replaying. It's over.", categoryId: 'overthinking' },
  { id: 'ot11', text: "You don't need more information. You need to decide.", categoryId: 'overthinking' },
  { id: 'ot12', text: "Your gut knows. Listen to it.", categoryId: 'overthinking' },
  { id: 'ot13', text: "Done thinking? Good. Now rest.", categoryId: 'overthinking' },
  { id: 'ot14', text: "The answer won't come from more worrying", categoryId: 'overthinking' },
  { id: 'ot15', text: "Let your mind rest. The solution might find you.", categoryId: 'overthinking' },
  { id: 'ot16', text: "You don't have to solve it right now", categoryId: 'overthinking' },
  { id: 'ot17', text: "Uncertainty is uncomfortable, not dangerous", categoryId: 'overthinking' },
  { id: 'ot18', text: "Sometimes there is no right answer", categoryId: 'overthinking' },

  // Peace (15)
  { id: 'pc1', text: "You deserve calm", categoryId: 'peace' },
  { id: 'pc2', text: "Not everything needs your attention right now", categoryId: 'peace' },
  { id: 'pc3', text: "Peace is possible, even in chaos", categoryId: 'peace' },
  { id: 'pc4', text: "Stillness is strength", categoryId: 'peace' },
  { id: 'pc5', text: "You're allowed to step back", categoryId: 'peace' },
  { id: 'pc6', text: "Find the quiet in the noise", categoryId: 'peace' },
  { id: 'pc7', text: "You don't have to fix everything", categoryId: 'peace' },
  { id: 'pc8', text: "Let go of what you can't control", categoryId: 'peace' },
  { id: 'pc9', text: "Create space for silence", categoryId: 'peace' },
  { id: 'pc10', text: "It's okay to do nothing", categoryId: 'peace' },
  { id: 'pc11', text: "Peace begins within", categoryId: 'peace' },
  { id: 'pc12', text: "You can choose calm", categoryId: 'peace' },
  { id: 'pc13', text: "Let the noise fade", categoryId: 'peace' },
  { id: 'pc14', text: "Protect your peace fiercely", categoryId: 'peace' },
  { id: 'pc15', text: "Calm is always available to you", categoryId: 'peace' },

  // Hard Days (20)
  { id: 'hd1', text: "Struggling doesn't mean failing", categoryId: 'hard-days' },
  { id: 'hd2', text: "You're allowed to have a bad day", categoryId: 'hard-days' },
  { id: 'hd3', text: "Tomorrow is a new chance, but today can just be today", categoryId: 'hard-days' },
  { id: 'hd4', text: "Surviving is enough sometimes", categoryId: 'hard-days' },
  { id: 'hd5', text: "It's okay to just exist today", categoryId: 'hard-days' },
  { id: 'hd6', text: "You don't have to be strong all the time", categoryId: 'hard-days' },
  { id: 'hd7', text: "This too shall pass", categoryId: 'hard-days' },
  { id: 'hd8', text: "You're not alone, even when it feels that way", categoryId: 'hard-days' },
  { id: 'hd9', text: "Bad days don't make a bad life", categoryId: 'hard-days' },
  { id: 'hd10', text: "You're doing the best you can", categoryId: 'hard-days' },
  { id: 'hd11', text: "It's okay to not have it together", categoryId: 'hard-days' },
  { id: 'hd12', text: "You've survived 100% of your worst days", categoryId: 'hard-days' },
  { id: 'hd13', text: "Gentle with yourself today", categoryId: 'hard-days' },
  { id: 'hd14', text: "You don't have to pretend to be okay", categoryId: 'hard-days' },
  { id: 'hd15', text: "Hard times don't last. Neither will this.", categoryId: 'hard-days' },
  { id: 'hd16', text: "It's okay to feel what you feel", categoryId: 'hard-days' },
  { id: 'hd17', text: "You're still here. That matters.", categoryId: 'hard-days' },
  { id: 'hd18', text: "One moment at a time", categoryId: 'hard-days' },
  { id: 'hd19', text: "The darkness will lift", categoryId: 'hard-days' },
  { id: 'hd20', text: "You're braver than you believe", categoryId: 'hard-days' },
];
